### ISSUE TITLE
[BE - ISSUE] 회원 가입 시 NullPointerException 발생

### ISSUE THREAD

**Issue by MyCatlikesChuru** [Travel-WithMe/TravelWithMe-sever#110]
## Issue 내용

- 회원가입시 mutipartfile 자체가 Null인 경우 500에러 발생. (NullPointerException)
- 에러핸들링이 필요해보임.
- String contentType = multipartFile.getContentType(); 해당 부분에서 발생.
- 추가로 FileUploadService 클래스의 this. 명시가 필요해보이는 메서드들이 존재합니다!

![](https://cdn.discordapp.com/attachments/1093421519608225964/1113394726054408222/2023-05-31_6.11.49.png)

**Comment by chanbinme** [comment]
최근 upstream에 머지한 코드에 memberService에서 multipartfile의 null처리하는 로직을 추가해두었습니다. 
upstream merge해보시고 확인해보시면 좋을듯합니다:)

```java
@Slf4j
@Service
@Transactional
@RequiredArgsConstructor
public class MemberService {

    ...

    private void uploadAndAndChangeImage(MultipartFile multipartFile,
                                         Member saveMember) {
        if (multipartFile != null) {
            String imageUrl = fileUploadService.upload(multipartFile, PROFILEIMAGE);
            saveMember.changeImage(imageUrl);
        }
    }
}
```
