### ISSUE TITLE
[BE - ISSUE] 회원가입 시 닉네임 에러 핸들링 오류

### ISSUE THREAD

**Issue by MyCatlikesChuru** [Travel-WithMe/TravelWithMe-sever#124]
## Issue 내용
어떠한 오류가 발생하였나요?

회원가입시 NickName에 동일한 유저로 가입하게된다면
500에러가 발생하고 에러핸들링이되지 않는 현상입니다 !

<img width="1046" alt="스크린샷 2023-06-13 오후 7 39 47" src="https://github.com/Travel-WithMe/TravelWithMe-sever/assets/95069395/dec4a849-92b3-4cec-adcf-912e9c7efd45">

<br/>

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE - ISSUE] 회원가입 오류 발생 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.

**Comment by chanbinme** [comment]
실제 서비스에서는 회원가입할 때 닉네임 중복 여부를 확인하는 api를 추가로 보냅니다.
유효성 검사별로 예러 핸들링 해야할까요?

**Comment by MyCatlikesChuru** [comment]
> 실제 서비스에서는 회원가입할 때 닉네임 중복 여부를 확인하는 api를 추가로 보냅니다. 그 때는 에러 유효성 검사별로 에러 핸들링 해야할까요?

아하 ! 이해하였습니다. 클라이언트 상에서는 중복이 API가 통과되어야지 사용가능하게 되어지기 때문에
해당 API에서는 따로 처리를 하지않으신것이군요!! 

개인적인 의견으로는 클라이언트측 흐름대로라면 아마 문제가 발생하지 않을 것으로 보이는데
API 개별로만 보았을때는 클라이언트에서 중복검사를 하지만 Nickname을 잘못 줄 경우에는 
동일한 문제가 발생될 것 같다고 생각이 들어서 추가하는게 괜찮아보이긴하는데 너무 리소스를 추가해놓는 것일까요?
어떤지 의견이 궁급합니다!!

**Comment by chanbinme** [comment]
에러 핸들링하는 이유가 사용자들에게 적절한 피드백을 전달해서 어떻게 행동해야할지 가이드를 주는 거라고 생각했었는데, 
nickname을 중복체크하지 않고 회원가입을 하려면 일반적인 방식으로 할 수 없기 때문에 일반적인 사용자라고 생각은 안들었습니다. 

일반적인 방법으로 접근하는 사용자라면 이미 중복 체크 로직을 통과한 nickname을 또 한 번 체크하게 되기 때문에 불필요한 쿼리가 날아가는게 아닐까 생각했습니다. 

이 에러가 Member Entity의 unique 규칙을 어긋나서 발생한걸텐데 필드마다의 유효성 검사 내용을 모두 에러 핸들링하진 않았어서 모든 유효성 검사에서 발생하는 예외도 핸들링 해줘야하는건지 고민이네용

**Comment by MyCatlikesChuru** [comment]
> 

넵 !! 확인하였습니다 ㅎㅎ !
